### ISSUE TITLE
Provide source distribution

### ISSUE THREAD

**Issue by pavelzw** [nephics/mat4py#12]
It would be nice if you provided the source distribution of your package on pypi. 
<img width="1096" alt="image" src="https://github.com/nephics/mat4py/assets/29506042/4ac54a73-0774-4c30-8645-81175cba0765">
This would make repackaging to conda easier.

**Comment by jcbsv** [comment]
There is now a new release v0.6.0 with a source distribution.

**Comment by jcbsv** [comment]
Link to release: https://pypi.org/project/mat4py/0.6.0/

**Comment by pavelzw** [comment]
Thanks!
