### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by RadekJanostik** [nephics/mat4py#4]
Hello,
thank you for your library. I would like to ask you for little modification. Nowadays it gives me two Deprecation Warnings. Namely:
`loadmat.py:14
  /mat4py/loadmat.py:14: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import Sequence
`
and 
`mat4py/savemat.py:15
 mat4py/savemat.py:15: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import Sequence, Mapping
`

It could be fixed be replacing imports from
`from collections import Sequence`
to 
`try:
    from collections.abc import Sequence
except ModuleNotFoundError:
    from collections import Sequence`
and from 
`from collections import Sequence, Mapping`
to
`try:
    from collections.abc import Sequence, Mapping
except ModuleNotFoundError:
    from collections import Sequence, Mapping
`
Or just check: https://stackoverflow.com/a/53978543
Could you, please, fix this issue and provide new version into pipy?
Thank you.

**Comment by tirkarthi** [comment]
I have created for https://github.com/nephics/mat4py/pull/5 to fix this. Thanks.

**Comment by RadekJanostik** [comment]
Thank you very much,
are you planing add new version to pip?
Thank you.
RJ

**Comment by jcbsv** [comment]
See https://pypi.org/project/mat4py/0.4.3

**Comment by RadekJanostik** [comment]
Thank you, you are the best.
RJ
